//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Tutorial Moodle IFTO

== Primeiro Acesso

Para ter acesso a plataforma Moodle é necessário que tanto o professor quanto o aluno esteja cadastrado na plataforma. Este cadastro é efetuado pela equipe de suporte da mesma, em caso de problemas com acesso, entrar em contato através do e-mail: https://moodle.palmas@ifto.edu.br.

Professores e Alunos devem utilizar os mesmos dados de acesso ao sistema acadêmico SIGA.

Professores devem utilizar a matrícula como login,  já alunos o CPF (somente números).

Existem dois ambientes Moodle principais no IFTO:
- Moodle Reitoria: apenas cursos do ensino à distância, endereço: https://moodlepalmas.ifto.edu.br
- Moodle Palmas: cursos presenciais do campus Palmas, endereço: http://moodlepalmas.ifto.edu.br

NOTA: Estudantes tentam equivocadamente acessar o Moodle da Reitoria.

== Vídeo de apresentação para primeiro acesso

video::sBTjg_I-nTQ[youtube,width=640,height=480]

== RECURSOS DO MOODLE

=== Inserir um recurso URL em um curso no Moodle

Para inserir uma URL em um curso no Moodle, em modo de edição, adicione um novo recurso URL. Mais informações no vídeo a seguir.

video::JRpzsJvlOj0[youtube,width=640,height=480]
