//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Programação para Dispositivos Móveis I
Fagno Alves Fonseca <fagno.fonseca@ifto.edu.br>
Mestre em Modelagem Computacional de Sistemas – UFT.

== Ação evento OnClick Botão - Exemplo 1

.Exemplo 1
[source, java]
----
    Button btn1 = findViewById(R.id.button1);
    btn1.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {

            Toast.makeText(getActivity(),"Olá Turma!",Toast.LENGTH_LONG).show();

        }
    });
----

== Ação evento OnClick Botão - Exemplo 2

.Exemplo 2
[source, java]
----
    Button btn1 = findViewById(R.id.button1);
    btn1.setOnClickListener(acaobotao());

    private View.OnClickListener acaobotao() {
        return new Button.OnClickListener(){
            @Override
            public void onClick(View v) {
                Toast.makeText(getActivity(),"Olá Turma, exemplo 2!",Toast.LENGTH_LONG).show();
            }
        };
    }

----

== Ação evento OnClick Botão - Exemplo 3

Você deve definir o layout a propriedade onClick
[source, xml]
----
<Button
        android:id="@+id/button1"
        android:onClick="acaobotao"/>
----

.Exemplo 2
[source, java]
----
    public void acaobotao(View view) {
            Toast.makeText(getActivity(),"Olá Turma, exemplo 3!",Toast.LENGTH_LONG).show();
    }
    
----




// [source, java]
// ----
// public class Pessoa{

//     private String nome;
//     private int idade;

//     public String getNome(){
//         return nome;
//     }

//     public int getIdade(){
//         return idade;
//     }

// }
// ----

// == Código fonte (incluir código fonte)
// .Título Código
// [source, java]
// ----
// include::Quadrado.java[]
// ----


// == Código fonte (Trecho do código fonte)
// .Título Código
// [source, java]
// ----
// //add a tag dentro do código ( tag::main[] e finalizar ( end::main[] ) )
// include::Teclado.java[tag=main]
// ----

// == Link para outro README 
// link:comandos/[Lista de Comandos]

