//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Tutorial Moodle IFTO

MOODLE é o acrônimo de "Modular Object-Oriented Dynamic Learning Environment", um software livre, de apoio à aprendizagem. A expressão designa ainda o Learning Management System (Sistema de gestão da aprendizagem) em trabalho colaborativo baseado nesse software ou plataforma, acessível através da Internet ou de rede local. 

Este tutorial foi construído a fim de apresentar as principais funcionalidades da plataforma aos professores e alunos do IFTO.

A seguir apresentamos tópicos para professores e alunos:

1. link:topics/Professor.adoc[Tutorial para Professores]

2. link:topics/Aluno.adoc[Tutorial para Alunos]

IMPORTANT: Em caso de dúvidas entre em contato com o suporte moodle através do endereço de e-mail: moodle.palmas@ifto.edu.br