//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Tutorial Moodle IFTO

== Primeiro Acesso

Para ter acesso a plataforma Moodle é necessário que tanto o professor quanto o aluno esteja cadastrado na plataforma. Este cadastro é efetuado pela equipe de suporte da mesma, em caso de problemas com acesso, entrar em contato através do e-mail: https://moodle.palmas@ifto.edu.br.

Professores e Alunos devem utilizar os mesmos dados de acesso ao sistema acadêmico SIGA.

Professores devem utilizar a matrícula como login,  já alunos o CPF (somente números).

Existem dois ambientes Moodle principais no IFTO:

- Moodle Reitoria: apenas cursos do ensino à distância, endereço: https://moodlepalmas.ifto.edu.br
- Moodle Palmas: cursos presenciais do campus Palmas, endereço: http://moodlepalmas.ifto.edu.br

NOTA: Estudantes tentam equivocadamente acessar o Moodle da Reitoria.

== Vídeo de apresentação para primeiro acesso

video::sBTjg_I-nTQ[youtube,width=640,height=480]

== RECURSOS E ATIVIDADES DO MOODLE

Existem diversos recursos e atividades na plataforma Moodle. Este tutorial apresenta alguns dos mais utilizados por professores em suas aulas. O Vídeo a seguir apresenta como adicionar um atividade ou recurso dentro do Moodle.

video::o42C_rjNPv8[youtube,width=640,height=480]

== RECURSOS

=== Inserir um recurso URL em um curso no Moodle

O módulo de URL permite que um professor para fornecer um link de web como um recurso do curso. Qualquer coisa que esteja livremente disponível on-line, como documentos ou imagens, pode ser vinculada.

Há uma série de opções de exibição para URL, como incorporado ou aberto em uma nova janela.

Observe que URLs também podem ser adicionados a qualquer outro tipo de recurso ou atividade através do editor de texto.

Para inserir uma URL em um curso no Moodle, ative o modo de edição e adicione um novo recurso URL. Mais informações no vídeo a seguir.

video::JRpzsJvlOj0[youtube,width=640,height=480]

=== Criando um recurso Rótulo em um curso Moodle

Um rótulo permite que texto e imagens possam ser inserido na página do curso. Rótulos são muito versáteis e podem ajudar a melhorar a aparência de um curso caso utilizado sabiamente.

Rótulos podem ser utilizados:

- Para separar uma lista de atividades com uma cabeçalho ou uma imagem;
- Para exibir vídeo diretamente na página do curso;
- Para adicionar uma descrição breve a uma seção de um curso.

Para inserir um rótulo em um curso no Moodle, ative o modo de edição e adicione um novo recurso Rótulo. Mais informações no vídeo a seguir.

video::wvMaj_K-Zm4[youtube,width=640,height=480]

=== Inserindo um recurso arquivo em um curso no Moodle

O módulo de arquivo permite que um professor forneça um arquivo de qualquer tipo como um recurso do curso. Sempre que possível, o arquivo será exibido na interface do curso, caso contrário, os estudantes serão levados a fazer o download. 

Note-se que os estudantes precisam ter o software adequado em seus computadores para abrir o arquivo.

Para inserir um arquivo em um curso no Moodle, ative o modo de edição e adicione um novo arquivo. Mais informações no vídeo a seguir.

video::dTW25ZjapmY[youtube,width=640,height=480]

=== Enviando e recebendo mensagens através do Moodle

O recurso Arquivo permite ao professor disponibilizar qualquer tipo de arquivo dentro do curso. 

Para inserir um arquivo em um curso no Moodle, ative o modo de edição e adicione um novo arquivo. Mais informações no vídeo a seguir.

video::xzvSUXKKNGw[youtube,width=640,height=480]

== ATIVIDADES

