//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Google Meet

Com o Google Meet você cria reuniões sem se preocupar se colegas de equipe ou clientes têm a conta ou os plug-ins certos. Com uma interface rápida e leve e o gerenciamento inteligente de participantes, é bem fácil fazer videochamadas com várias pessoas.

Como o Meet é totalmente integrado ao G Suite, você pode participar de reuniões a partir de um evento do Agenda ou um convite por e-mail. Todos os detalhes importantes do evento estão disponíveis quando necessário: seja em um laptop, um smartphone ou uma sala de conferências.

== Iniciar uma videochamada

video::55gAGcbddxI[youtube,width=640,height=480]

== Programar uma videochamada no Agenda

video::K-xEKOlGPB8[youtube,width=640,height=480]

== Aplicativo Google Meet

Participe das reuniões mesmo quando você não estiver na sua mesa de trabalho.
Com os aplicativos Meet criados especialmente para iOS e Android, você pode ver no Agenda as reuniões do dia, com todas as informações importantes. Basta um toque para participar. O G Suite Enterprise também cria um número de telefone de discagem para cada reunião, assim todos os convidados têm a experiência ideal, mesmo fora do escritório sem acesso a Wi-Fi ou dados.

Download https://play.google.com/store/apps/details?id=com.google.android.apps.meetings/[Google Play]

Download link:https://apps.apple.com/br/app/hangouts-meet-do-google/id1013231476/[Apple Store]


