//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela


= Tutorial Moodle IFTO

A plataforma MOODLE (Modular Object-Oriented Dynamic Learning Environment) é um software livre, de apoio à aprendizagem. Um Sistema de gestão da aprendizagem em trabalho colaborativo acessível através da Internet ou de rede local. Atualmente é a plataforma utilizada pelo Instituto Federal do Tocantins - IFTO nos cursos de modalidade a distância e também como instrumento de apoio ao ensino presencial.

Este tutorial foi construído a fim de apresentar as principais funcionalidades da plataforma aos professores e alunos do IFTO.

A seguir apresentamos tópicos com conteúdo para professores e alunos:

1. link:topics/professor.adoc[Tutorial para Professores]

2. link:topics/aluno.adoc[Tutorial para Alunos]

IMPORTANT: Em caso de dúvidas entre em contato com o suporte moodle através do endereço de e-mail: moodle.palmas@ifto.edu.br
