
//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

link:https://fagno.github.io/moodle-tutorial/[HOME]

== GOOGLE MEET

== Iniciar uma videochamada
Descrição: criar uma vídeochamada usando o Google Meet.

video::55gAGcbddxI[youtube,width=640,height=480]

== Programar uma videochamada no Agenda
Descrição: programar uma vídeochamada no Agenda através do Google Meet.

video::K-xEKOlGPB8[youtube,width=640,height=480]

== Aplicativo Google Meet

Participe das reuniões mesmo quando você não estiver na sua mesa de trabalho.
Com o aplicativo Meet criado especialmente para iOS e Android, você pode ver no Agenda as reuniões do dia com todas as informações importantes. Basta um toque para participar.

Download https://play.google.com/store/apps/details?id=com.google.android.apps.meetings/[Google Play]

Download link:https://apps.apple.com/br/app/hangouts-meet-do-google/id1013231476/[Apple Store]


