//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

link:https://fagno.github.io/moodle-tutorial/[HOME]

= Tutorial Google Classroom 

Google Classroom é um sistema de gerenciamento de conteúdo para escolas que procuram simplificar a criação, a distribuição e a avaliação de trabalhos. Ele é um recurso do Google Apps para a área de educação.

Vídeos aulas elaboradas pelo professor Claudio Monteiro - IFTO Campus Palmas e-mail: ccm@ifto.edu.br

== Classroom Professores

Descrição: Uso do Google Classroom por professores.

video::JnGXGApOwXU[youtube,width=640,height=480]

== Transmissão ao vivo no YouTube

Descrição: Transmissão de vídeo ao vivo com compartilhamento de tela no YouTube.

video::wsdW4L73DH0[youtube,width=640,height=480]

== Enviando um vídeo ao YouTube

Descrição: Como enviar um vídeo ao Youtube através do celular.

video::5YC3RnLPlvk[youtube,width=640,height=480]

== Video aulas direto do celular

Descrição: Gravando vídeos com ADV Recorder.

video::bCE_0VEO0rc[youtube,width=640,height=480]
